### ISSUE TITLE
state file mass center mismatch

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#145]
Re-starting with state file generated by the following input fails:

``` bash
./input.yml | faunus -s state.json
```

``` yaml
temperature: 298
random: {seed: fixed}
geometry: {type: hexagonal, length: 100, radius: 100}
mcloop: {macro: 10, micro: 10}

atomlist:
    - HD:   {sigma: 4.64, eps: 2.252473636363636, dp: 2, alphax: -11}
    - TL1:  {sigma: 6.56, eps: 2.252473636363636, dp: 2, alphax: -20}
    - TL2:  {sigma: 8, eps: 2.252473636363636, dp: 2, alphax: -20}
    - AM:   {sigma: 2.4, eps: 2.252473636363636, dp: 2}
    - HAM:  {sigma: 2.4, eps: 2.252473636363636, dp: 2, q: 1}
    - NA:   {sigma: 4.6, eps: 0.01, dp: 30, q: 1}
    - CL:   {sigma: 4.6, eps: 0.01, dp: 30, q: -1}
    - H:    {pactivity: 4, implicit: True}

moleculelist:
    - Na: {atoms: [NA], atomic: True, activity: 0.112}
    - Cl: {atoms: [CL], atomic: True, activity: 0.112}
    - lipid:
        structure:
            - AM:  [0,0,0]
            - HD:  [0,0,3.5199999999999996]
            - TL1: [0,0,9.12]
            - TL2: [0,0,16.4]
            
        bondlist:
            - fene: {index: [0,1], k: 1.0558470170454544, rmax: 5.279999999999999,
                    sigma: 3.5199999999999996, eps: 2.252473636363636}
            - fene: {index: [1,2], k: 1.0558470170454544, rmax: 8.399999999999999,
                    sigma: 5.6, eps: 2.252473636363636}
            - fene: {index: [2,3], k: 1.0558470170454544, rmax: 10.919999999999998,
                    sigma: 7.279999999999999, eps: 2.252473636363636}

            - harmonic: {index: [0,2], k: 0.35194900568181814, req: 18.159999999999997}
            - harmonic: {index: [1,3], k: 0.35194900568181814, req: 25.64}
            
insertmolecules:
    - Na: {N: 200, inactive: True}
    - Cl: {N: 200, inactive: True}
    - lipid: {N: 160}

energy:
    - customexternal: 
        molecules: [lipid]
        com: false
        constants: {radius: 12}
        function:
            var r2 := x^2 + y^2;
            if ( r2 < radius^2 )
               1e10;
            else
               0;
    - bonded: {}
    - nonbonded:
        cutoff_g2g: 50
        default:
            - wca: {mixing: LB}
            
        TL1 TL1:
            - wca:
                mixing: LB
            - cos2: {rc: 7.36335072, eps: 2.252473636363636, wc: 11.152}
        TL1 TL2:
            - wca:
                mixing: LB
            - cos2: {rc: 8.17152336, eps: 2.252473636363636, wc: 12.376}
        TL2 TL2:
            - wca:
                mixing: LB
            - cos2: {rc: 8.979696, eps: 2.252473636363636, wc: 13.6}
        NA HD:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}
        NA TL1:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}
        NA TL2:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}
        CL HD:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}
        CL TL1:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}
        CL TL2:
            - wca:
                mixing: LB
            - polar: {epsr: 78.47995215311005}

moves:
    - moltransrot: {molecule: lipid, dp: 0.5, dprot: 0.5, repeat: 10}
        
analysis:
    - systemenergy: {file: energy_0.dat, nstep: 10}
    - savestate: {file: state.json}
    - savestate: {file: confout.pqr}
    - sanity: {nstep: 1}

```
