### ISSUE TITLE
Reimplement mixing rules for non-bonded potentials

### ISSUE THREAD

**Issue by rc83** [mlund/faunus#159]
1. The coefficient matrices are implemented like PairMatrix inside the respective potential.
2. PairMatrix is constructed using a Mixer class which takes a vector of AtomType, a lambda function to extract the property (e.g., sigma, epsilon) from the AtomType and an actual combining function (e.g., arithmetic or geometric average). We do not assume the mixing depends on other parameters, i.e., the sigma value can be computed solely from a pair of sigma values.
3. The Potential class can override any default pair parameters. That will be used for custom pair values. The custom pair values are internally treated as AtomType.
4. Serialization to JSON shall check if the parameters in the matrices correspond to the mixing rules; otherwise they shall be output as custom pairs.
5. Serialization from JSON shall be greatly simplified.

**Comment by rc83** [comment]
SquareWell potential assumes a squared value of the attractive diameter in the parameter matrix. However the mixing rule provided a plain value of the attractive diameter. The inconsistency has been fixed during the refactorisation.

**Comment by rc83** [comment]
Work in progress with the reimplementation basically done. It remains:
1. unittests
2. universal mapping of json string to the mixer type + allowed combinations of mixers and potentials
3. better incorporation of the logger

**Comment by mlund** [comment]
Using the `custom` keyword, the following is serialised to json,
``` yaml
          -   lennardjones:
                    custom:
                    -   Na+ Cl-:
                            activity: 0.0
                            alphax: 0.0
                            dp: 0.0
                            dprot: 0.0
                            eps: 0.01
                            id: -1
                            mu: [0.0, 0.0, 0.0]
                            mulen: 0.0
                            mw: 1.0
                            pactivity: null
                            q: 0.0
                            scdir: [1.0, 0.0, 0.0]
                            sclen: 0.0
                            sigma: 4.6
                            tension: 0.0
                            tfe: 0.0
                    -   Na+ GLU:
                            activity: 0.0
                            alphax: 0.0
                            dp: 0.0
                            ...
```
which could be slightly confusing as one would normally want to see only i.e. `sigma` and `eps`
