### ISSUE TITLE
Splining of Yukawa fails

### ISSUE THREAD

**Issue by mlund** [mlund/faunus#301]
Using `nonbonded_splined` with Yukawa potentials fails as the energy doesn't seem to go to zero at the cutoff. In turn this triggers an infinite loop here: https://github.com/mlund/faunus/blob/f94ab0c1036e7b2e54f00ce02243591a40628207/src/potentials.cpp#L556

Under the hood, yukawa is `CoulombGalore::Poisson` with `C=1` and `D=-1`.

Example:

``` yml
    - nonbonded_splined:
        default: 
            - lennardjones: {mixing: LB}
            - coulomb: {type: yukawa, epsr: 80, cutoff: 100, debyelength: 100}
```

Ping @bjornstenqvist 

Todo:
- [x] eliminate infinite look (#302)
- [x] fix yukawa shifting (#312)
